version: "3.9"

networks:
  traefik-public:
    driver: overlay
    attachable: true

services:

  traefik:
    image: traefik:v3.6

    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false
      - --entrypoints.web.address=:80

    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - traefik-public

    deploy:
      placement:
        constraints:
          - node.role==manager

  client-a:
    image: pratik6958/client-a:latest

    networks:
      - traefik-public

    deploy:
      replicas: 3
      labels:
        - traefik.enable=true

        - traefik.http.routers.client-a.rule=PathPrefix(`/client-a`)
        - traefik.http.routers.client-a.entrypoints=web
        - traefik.http.routers.client-a.middlewares=client-a-strip

        - traefik.http.middlewares.client-a-strip.stripprefix.prefixes=/client-a

        - traefik.http.services.client-a.loadbalancer.server.port=3000


  client-b:
    image: pratik6958/client-b:latest

    networks:
      - traefik-public

    deploy:
      replicas: 3
      labels:
        - traefik.enable=true

        - traefik.http.routers.client-b.rule=PathPrefix(`/client-b`)
        - traefik.http.routers.client-b.entrypoints=web
        - traefik.http.routers.client-b.middlewares=client-b-strip

        - traefik.http.middlewares.client-b-strip.stripprefix.prefixes=/client-b

        - traefik.http.services.client-b.loadbalancer.server.port=8000


  prometheus:
    image: prom/prometheus:latest

    networks:
      - traefik-public

    deploy:
      replicas: 1
      labels:
        - traefik.enable=true

        - traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)
        - traefik.http.routers.prometheus.entrypoints=web
        - traefik.http.routers.prometheus.middlewares=prom-strip

        - traefik.http.middlewares.prom-strip.stripprefix.prefixes=/prometheus

        - traefik.http.services.prometheus.loadbalancer.server.port=9090


  grafana:
    image: grafana/grafana:latest

    networks:
      - traefik-public

    deploy:
      replicas: 1
      labels:
        - traefik.enable=true

        - traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)
        - traefik.http.routers.grafana.entrypoints=web
        - traefik.http.routers.grafana.middlewares=grafana-strip

        - traefik.http.middlewares.grafana-strip.stripprefix.prefixes=/grafana

        - traefik.http.services.grafana.loadbalancer.server.port=3000
