version: "3.9"

networks:
  traefik-public:
    driver: overlay
    attachable: true

volumes:
  prometheus-data:
  grafana-data:

services:

  traefik:
    image: traefik:v3.6

    command:
      - --api.dashboard=true
      - --api.insecure=true

      # Swarm provider (REQUIRED for Docker Swarm)
      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false

      # Entry point
      - --entrypoints.web.address=:80

      # Logging
      - --log.level=INFO

    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - traefik-public

    deploy:
      placement:
        constraints:
          - node.role==manager

  # =========================
  # CLIENT A (NODEJS PORT 3001)
  # =========================
  client-a:
    image: pratik6958/client-a:latest

    networks:
      - traefik-public

    deploy:
      replicas: 3

      labels:
        - traefik.enable=true

        # Router
        - traefik.http.routers.client-a.rule=PathPrefix(`/client-a`)
        - traefik.http.routers.client-a.entrypoints=web

        # Middleware
        - traefik.http.middlewares.client-a-strip.stripprefix.prefixes=/client-a
        - traefik.http.routers.client-a.middlewares=client-a-strip

        # Service port (IMPORTANT → 3001)
        - traefik.http.services.client-a.loadbalancer.server.port=3001


  # =========================
  # CLIENT B (FASTAPI PORT 8000)
  # =========================
  client-b:
    image: pratik6958/client-b:latest

    networks:
      - traefik-public

    deploy:
      replicas: 3

      labels:
        - traefik.enable=true

        # Router
        - traefik.http.routers.client-b.rule=PathPrefix(`/client-b`)
        - traefik.http.routers.client-b.entrypoints=web

        # Middleware
        - traefik.http.middlewares.client-b-strip.stripprefix.prefixes=/client-b
        - traefik.http.routers.client-b.middlewares=client-b-strip

        # FastAPI port
        - traefik.http.services.client-b.loadbalancer.server.port=8000


  # =========================
  # PROMETHEUS
  # =========================
 
prometheus:
  image: prom/prometheus:latest

  volumes:
    - prometheus-data:/prometheus

  networks:
    - traefik-public

  command:
    - --web.external-url=/prometheus
    - --web.route-prefix=/

  deploy:
    replicas: 1

    labels:
      - traefik.enable=true

      - traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)
      - traefik.http.routers.prometheus.entrypoints=web

      - traefik.http.middlewares.prometheus-strip.stripprefix.prefixes=/prometheus
      - traefik.http.routers.prometheus.middlewares=prometheus-strip

      - traefik.http.services.prometheus.loadbalancer.server.port=9090

  # =========================
  # GRAFANA
  # =========================
   grafana:
  image: grafana/grafana:latest

  volumes:
    - grafana-data:/var/lib/grafana

  networks:
    - traefik-public

  environment:
    - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
    - GF_SERVER_SERVE_FROM_SUB_PATH=true

  deploy:
    replicas: 1

    labels:
      - traefik.enable=true

      - traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)
      - traefik.http.routers.grafana.entrypoints=web

      - traefik.http.middlewares.grafana-strip.stripprefix.prefixes=/grafana
      - traefik.http.routers.grafana.middlewares=grafana-strip

      - traefik.http.services.grafana.loadbalancer.server.port=3000
